### ISSUE TITLE
Using with Express.js

### ISSUE THREAD

**Issue by nicgutierrez** [ngsru/vue-server#5]
Hi, kind of a noob question here.

How do I use this with express.js?

As a test, I'm doing the following but I feel that it's somehow "wrong".

```
vm.$on('vueServer.htmlReady', function(html) {
    app.get('/', function (req, res) {
      res.send(html);
    });

    var server = app.listen(3000, function () {
    });
});
```

Cheers.
Nic

**Comment by fullfs** [comment]
@nicgutierrez Hello!
Don't worry, its ok to don't get it :)

You go like this:

```javascript
var express = require('express')
var app = express();
var vueServer = require('vue-server');
var Vue = new vueServer.renderer();

app.get('/', function(req, res) {
    var vm = new Vue({
        template: '<div>Hello world!</div>',
    });

    vm.$on('vueServer.htmlReady', function(html) {
        res.send(html)
    });
});

var server = app.listen(3000, function () {
});
```

I'll add an ```example``` for the case, thanks.

**Comment by nicgutierrez** [comment]
Hi @fullfs.

Thanks for this, I get it now :)

One more quick (??) question ...

I know I can keep creating my routes with express, which is fine, but how can I integrate vue router here? What's the ideal workflow?

Cheers.
Nic

**Comment by fullfs** [comment]
@nicgutierrez Sorry, but can't provide you with proper answer for the quest right now. Actually I didn't ever tried using vue-router. We've got our own router engine on the project I'm writing ```vue-server``` for.
I'll try it some time later and will try understand how can we integrate it, ok? :)

**Comment by nicgutierrez** [comment]
hey @fullfs, no worries, it can wait ;)

Cheers
Nic
