### ISSUE TITLE
Support sync?

### ISSUE THREAD

**Issue by guoxmin** [ngsru/vue-server#7]
Support sync?

**Comment by fullfs** [comment]
@guoxmin Hello!
Lack examples here, yeah :(

If to strictly answer your question, the answer is no.
But, your question is probably about working with async data and actually you can work with it. Though ```vue-server``` has restrictions there.

Overall, ```vue-server``` has no reactivity. This means it has no watchers and does not detect props being changed. There are several reasons for its:
- Server-side rendered (SSR) html is not supposed to mutate after being sent
- You need a certain moment when server sends the html, so you can't just "wait for something" (some async request)
- Some technical reasons...

But there is a mechanism that imitates watchers. It's built on ```activateBe``` hook.

Please check out the example: https://github.com/ngsru/vue-server/blob/dev/examples/async-data/index.js (it's ```dev``` branch). I think you can get the idea.
And also please note that ```activateBe``` should be used only by one component in page. The one controls the moment all data recieved. If you use ```activateBe```, its ```done``` callback is a trigger for finish up the rendering.

**Comment by guoxmin** [comment]
@fullfs Tank you for answer! I mean `vm.$on('vueServer.htmlReady',function(html){}`  is async now,but i want to a sync way.

**Comment by fullfs** [comment]
@guoxmin Oh, I see. Look like I got it wrong :)
Well, sorry, there is no way right now to run it sync. Async mode is important for not to block event loop. But I will consider the option in future.

**Comment by guoxmin** [comment]
@fullfs Waiting for your contributions!

**Comment by fullfs** [comment]
@guoxmin Sorry, bringing sync mode is not planned in near future. Thanks for the suggestion :)
